const BREAK_INCREASE = 'BREAK_INCREASE';
const BREAK_DECREASE = 'BREAK_DECREASE';
const SESSION_INCREASE = 'SESSION_INCREASE';
const SESSION_DECREASE = 'SESSION_DECREASE';
// const START = 'START';
// const PAUSE = 'PAUSE';
// const RESET = 'RESET';
const SET_BREAK = 'SET_BREAK';
const SET_SESSION = 'SET_SESSION';
export {
  BREAK_INCREASE,
  BREAK_DECREASE,
  SESSION_INCREASE,
  SESSION_DECREASE,
  // START,
  // PAUSE,
  // RESET,
  SET_BREAK,
  SET_SESSION,
};
